### PR TITLE
Fixes Issue #57 by adding absolute dir capability

### PR DESCRIPTION
**Pull request by oniseijin**
For issue #57

### CODE REVIEW

**Comment by oniseijin** [comment]
Failure of build doesn't look to be anything related to change

**Comment by jkutner** [comment]
Yes, build failure is unrelated (we can't run CI on PRs because we use a secret key for some tests). Looking to merge now.

**Comment by jkutner** [comment]
I think we can actually do this without the extra cli option. I'm going to change what you've done to this:

```java
String expandedDirName = commandLineParams.expandedDirName;
Path expandedDirPath = Paths.get(expandedDirName);

if(expandedDirPath.isAbsolute()) {
  Host tempHost = tomcat.getHost();
  tempHost.setAppBase(new File(expandedDirName).getAbsolutePath()); // override defaults to use Host object within ExpandWar
  expandedDir = ExpandWar.expand(tempHost, fileUrl, "");
} else {
  expandedDir = ExpandWar.expand(tomcat.getHost(), fileUrl, "/" + expandedDirName);
}
```

If that ends up not working for you, we'll put the extra option back in.

**Comment by oniseijin** [comment]
Should work, one less option is always good if not necessary

**Pull request merged**
