### PR TITLE
Add the ability to specify the URIEncoding of the connector

### PR DESCRIPTION
**Pull request by flof**
I added the ability to specify the URIEncoding of the connector. It is the equivalent of setting the Attribute URIEncoding of the Connector-element in server.xml. This was necessary to support UTF-8 encoded query parameters.

### CODE REVIEW

**Comment by PawelJagus** [comment]
Hi, this issue seems to have been open for quite a while now. Was this parameter added after all?

**Comment by flof** [comment]
Hi,
sorry no. You can use my fork at https://github.com/flof/webapp-runner <https://github.com/flof/webapp-runner> , wich contains the feature.
And maybe you can leave a comment on the pull request and state that you need this feature too.

Florian

**Comment by jkutner** [comment]
Sorry this was overlooked. I'll try to get it merged soon.

**Comment by jkutner** [comment]
This same functionality was added by 6ff36cf50d87898665a9d4a6e0a73dcda96d930b

**Pull request closed without merging**
