### PR TITLE
update tomcat to 8.0.15 and add scanBootstrapClassPath parameter

### PR DESCRIPTION
**Pull request by mqshen**
update tomcat to 8.0.15 and add scanBootstrapClassPath command line parameter.

### CODE REVIEW

**Comment by jkutner** [comment]
Cool! Will get this merged soon. But I want to run some tests with it first. Thanks!

**Comment by mqshen** [comment]
Why the 

     mvn clean install -Pintegration-test 

test failed?
I haven't change the code relate to that.

**Comment by jkutner** [comment]
That failure is not your fault. The heroku-maven-plugin test requires an API key to run correctly, and Travis won't decrypt the encrypted API key when running tests against PRs for security reasons (because you could just print it out in plain text or something).

So you can ignore that. I need to exclude it from tests for PRs.

**Comment by jkutner** [comment]
I've found a couple issues that I'll need to fix before merging this into master. First, it looks like Tomcat 8 is trying to unpackWARs by default. This is easily fixed though:

```
((StandardContext) ctx).setUnpackWAR(false);
```

I'll add that and keep the manual expanding of the war file that webapp-runner does, and default it to false as in previous versions.

The second problem has to do with Redis. It looks like I'll need to upgrade ru.zinin:tomcat-redis-session to 0.7. I'm working on that now. I will also need to test Memcached.

**Comment by mqshen** [comment]
Cool! Thanks!

**Comment by jkutner** [comment]
Apologizes for the delay on this. The use of tomcat-redis-session is proving to be difficult. We will probably have to get a new 0.8 version of it.

**Comment by jkutner** [comment]
Progress: https://github.com/zinin/tomcat-redis-session/pull/11

**Comment by jkutner** [comment]
I moved these changes into a branch with some other changes:
https://github.com/jsimone/webapp-runner/tree/tomcat8

**Comment by jkutner** [comment]
I'm not sure why i didn't close this earlier.

**Pull request closed without merging**
